#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
from transformers import AutoModelForCausalLM , AutoTokenizer

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_NAME, MODEL_CACHE, TOKEN_CACHE

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

if not os.path.exists(TOKEN_CACHE):
    os.makedirs(TOKEN_CACHE)

# Download tokenizer
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True
)
tokenizer.save_pretrained(TOKEN_CACHE)

# Download model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True
)
model.save_pretrained(MODEL_CACHE)
